development:
      host: localhost
      adapter: mysql2
      database: mangu
      port: 3306
      username: root
      password: root

test: &test
      host: localhost
      adapter: mysql2
      database: mangunow
      port: 3306
      username: root
      password: root
production:
      host: localhost
      adapter: mysql2
      database: manguthen
      port: 3306
      username: root
      password: root
cucumber:
  <<: *test
